version: "3"

services:
  fluttershub.com:
    image: registry.gitlab.com/mrflutters/fluttershub:latest
    restart: always
    networks:
      - external
    container_name: fluttershub.com
  # www.dev.fluttershub.com:
  #   image: registry.gitlab.com/mrflutters/fluttershub:dev
  #   restart: always
  #   networks:
  #     - external
  #   container_name: www.dev.fluttershub.com
networks:
  external:
    external: true
