version: "3"

services:
  fluttershub-homepage:
    image: ghcr.io/fluttershub/homepage:x64-latest
    restart: always
    networks:
      - external
    container_name: fluttershub.com
    labels:
      - "traefik.enable=true"
networks:
  external:
    external: true
