version: "3"

services:
  home:
    image: registry.gitlab.com/mrflutters/flutters-website-dockertesting:dev
    restart: always
    networks:
      - external
    container_name: Fluttershub_home
networks:
  external:
    external: true
