version: "3"

services:
  fluttershub.com:
    image: ghcr.io/hotarublaze/fluttershub:latest
    restart: always
    networks:
      - external
    container_name: fluttershub.com
    labels:
      - "traefik.enable=true"
networks:
  external:
    external: true
