version: "3"

services:
  fluttershub.com:
    image: registry.gitlab.com/mrflutters/fluttershub:latest
    restart: always
    container_name: fluttershub.com
  dev.fluttershub.com:
    image: registry.gitlab.com/mrflutters/fluttershub:dev
    restart: always
    container_name: dev.fluttershub.com
networks:
  external:
    external: true
